// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package ads.poo;

// import org.slf4j.Logger;
// import org.slf4j.LoggerFactory;

// // import java.util.logging.Level;
// // import java.util.logging.Logger;

// public class App {

//     // private static final Logger LOGGER = Logger.getLogger(App.class.getName());
//     // public static void main(String[] args) {

//     //     LOGGER.setLevel(Level.FINEST);


//     //     LOGGER.fine("Mensagem de depuração");
//     //     LOGGER.info("Aplicação iniciado com sucesso");
//     //     LOGGER.warning("Número de matrícula inválido");
//     //     LOGGER.severe("Conexão perdida com o banco de dados");     

//     // }

//     private static final Logger LOGGER = LoggerFactory.getLogger(App.class);



//     public static void main(String[] args) {
//         // LOGGER.debug("Requisição recebida do IP: {}", "192.168.1.1");
//         // LOGGER.info("Usuário: {}", "juca");
//         // LOGGER.warn("Conexão perdida com o banco de dados. Tentando novamente");
//         // LOGGER.error("Falha ao escrever {} no arquivo {}" , 123 , "matriculas.txt");

        


//         Pessoa p = new Pessoa("Luca", "096.695.979.51");

//         p.getCpf();

//     }


// }
