/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

public class App {
    Scanner teclado = new Scanner(System.in);
    private HashMap<String, Aluno> bancoDeDados;
    private Object alunos;
    
    public App(){
        this.bancoDeDados = new HashMap<>();
    }

    private int menu(){
        int opcao = 0;
        System.out.println("..:: SIGAA 2 ::.."); 
        System.out.println("Entre com a opção desejada");
        System.out.println("1 - Cadastrar");
        System.out.println("2 - Editar");
        System.out.println("3 - Excluir");
        System.out.println("4 - Listar dados de um aluno");
        System.out.println("5 - Listar todos os dados");
        System.out.println("6 - Sair");
        opcao = teclado.nextInt();
        teclado.nextLine();
        return opcao;
    }

    private void listarTodos(){
        System.out.println(this.alunos);
    }

    private boolean cadastrar(){
        System.out.println("Entre com nome :");
        String nome = teclado.nextLine();
        System.out.println("Entre com a matrícula :");
        String matricula = teclado.nextLine();
        System.out.println("Entre com o curso :");
        String curso = teclado.nextLine();
        System.out.println("Entre com seu telefone :");
        String telefone = teclado.nextLine();
        System.out.println("Entre com seu email :");
        String email = teclado.nextLine();
        System.out.println("Entre com sua data de nascimento :");
        String dataString = teclado.nextLine();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(dataString, formato);
        
    }

    private boolean cadastrar(){
        String matricula = "123";
        Aluno a = new Aluno("Juca", matricula, "Ads", "48", "juca@ee", LocalDate.of(2000, 10, 2));
        return this.alunos.app(a);

        if(this.bancoDeDados.containsKey(matricula)){
            this.bancoDeDados.put(matricula, a);
            return true;
        }
        return false;
    }


    private void excluir(){
        String matricula ="123";

        if (this.bancoDeDados.remove(matricula) == null){
            System.out.println("Não encontrado");
        }else{
            System.out.println("Removido com sucesso");
        }
    }



    
    public static void main(String[] args) {
        App app = new App()
        int opcao;

        do {
            opcao=app.menu();

            switch(opcao) {
                case 1 -> System.out.println("Cadastrando");
                case 2 -> System.out.println("Editando");
                case 3 -> System.out.println("Excluindo");
                case 4 -> System.out.println("Listando dados");
                case 5 -> System.out.println("Listando alunos");
                default -> System.out.println("Opção inválida");
            }
        } while (opcao!=6);
            
    }
}
