/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.produtos.Dimensao;
import ads.poo.produtos.SemFio;
import ads.poo.produtos.Telefone;

public class App {
    public static void main(String[] args) {
        Telefone tel = new Telefone(12564, "123356ad", "fixo" , 1.56 , new Dimensao(2,5,6));
        Telefone telsemfio = new SemFio(25468, "121545sa65s", "semfio", 1.0, new Dimensao(4,5,6) , 3.4, 14, 5000);
    
        System.out.println(tel.imprimirDados());
        System.out.println(telsemfio.imprimirDados());
    }
}
