/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Ponto p = new Ponto("vermelho", 2, 3);
        Linha l = new Linha("marrom", Ponto(), p);
        
    }
}
