/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Scanner;
import java.util.stream.Stream;

public class App {  
    public static void main(String[] args) {
        String currentDir = System.getProperty("user.dir");

        Path inicial = Path.of(currentDir+"/novo.txt");
 
        // if (Files.exists(path)) {
        //     System.out.println(String.format("Arquivo: %s" , path.toAbsolutePath()));
        //     System.out.println(String.format("Regular: %s" , Files.isRegularFile(path)));
        //     System.out.println(String.format("Diretório: %s" , Files.isDirectory(path)));
        //     System.out.println(String.format("Permissão de leitura: %s" , Files.isReadable(path)));
        //     System.out.println(String.format("Permissão de escrita: %s" , Files.isWritable(path)));
        // }else{
        //     System.out.println("Arquivo não encontrado");
        // }

        // try {
        //     Files.createFile(path);
        //     System.out.println("Arquivo criado");

        //     Path novoPath = Path.of(currentDir+"/arquivo-renomeado.txt");
        //     Files.move(path, novoPath);
        //     System.out.println("Arquivo Movido");

        //     Files.deleteIfExists(novoPath);
        //     System.out.println("Arquivo excluído");

        // }catch (Exception e ){
        //     System.err.println("Erro: + " +e);
        // }

        try (Stream<Path> walk = Files.walk(inicial)) {
            walk.sorted().forEach(arq -> {

                int profundidade = inicial.relativize(arq).getNameCount();
                String sufixo = (Files.isDirectory(arq) ? " (d)" : "");
                System.out.println(" ".repeat(profundidade )+ arq.getFileName() + sufixo);
            });
        } catch(Exception e) {
            System.err.println(e);
        }
    }
}
