/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;
public class App{

    public static void main(String[] args) {

        Carro c = new Carro();
        Carro d = new Carro();

        System.out.println("Velocidade:" + c.obterVelocidade());

        c.acelerar(10);

        System.out.println("Velocidade:" + c.obterVelocidade());

        System.out.println("Velocidade: " + d.obterVelocidade());

        d.acelerar(50);

        System.out.println("Velocidade:" + d.obterVelocidade());

    }
}

